#!/usr/bin/env bash
set -euo pipefail

# Get a list of staged .nix files
STAGED_FILES=()
while read f; do
  STAGED_FILES+=("${f}")
done < <(git diff --cached --name-only --diff-filter=ACM | grep '\.nix$' || true)

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

if ! out=$(nix fmt -- --ci "${STAGED_FILES[@]}"); then
  echo "${out}" >&2
  echo "❌ some files are not formatted correctly. Run 'make nixfmt'." >&2
fi
